name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Deploy to EC2
        uses: appleboy/scp-action@v1
        with:
          host: '54.167.93.19'
          username: 'ec2-user'
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          source: '.'
          target: '/home/ec2-user'

      - name: Deploy to S3
        uses: aws-actions/s3-upload@v1
        with:
          aws-region: 'us-east-1'
          bucket: 'myfrontendbucket9909'
          source: 'frontend'
          destination: '/'