name: deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: reggionick/s3-deploy@v4
        with:
          folder: frontend
          bucket: myfrontendbucket9909
          bucket-region: us-east-1
          files-to-include: index.html